name: Deploy Website via FTP

on:
  push:
    branches:
      - master # Set to your default branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    name: Deploy via FTP
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: "ftp.pasjihotel-kosmatincek.si"
        username: ${{ secrets.test1 }}
        password: ${{ secrets.test123btcz }}
        local-dir: "./test1" # Set your local directory
        # Add 'server-dir' if needed to specify the directory on the server
        # Remove 'git-ftp-args' or replace with appropriate inputs like 'exclude' or 'dry-run' if needed
