name: Deploy Website via FTP

on:
  push:
    branches:
      - master # Set to your default branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    name: Deploy via FTP

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        ftp-server: "ftp.pasjihotel-kosmatincek.si"
        ftp-username: ${{ secrets.FTP_test1 }}
        ftp-password: ${{ secrets.FTP_test123btcz }}
        local-dir: "./" # Set your local directory
        git-ftp-args: --insecure # Remove if your FTP server supports FTPS
